### ISSUE TITLE
De facut primul push in repo

### ISSUE THREAD

**Issue by bogdan-iamnitchi-school** [BRA-Team/test-frontend#2]
Verificam ca totul merge bine si suntem logati cu conturile care trebuie

### Nu uitati ca folosim ssh key

1.  cd ~\.ssh  -> navigam in folderul ssh
2.  ls -> daca exista deja un file id_ed25519.pub nu mai faceti nimic
3.  ls -> daca nu exista atunci folositi ssh-keygen -t ed25519 -C "your_email@example.com"
4.  copiati ce contine id_ed25519.pub in github la settings ssh key

**Comment by radumihai2002** [comment]
am facut
